import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { ProductContextProvider } from './product.context';

const font = Roboto({ weight: "500", subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ProductContextProvider>{children}</ProductContextProvider>
      </body>
    </html>
  )
}
